# Generated by Django 3.2.12 on 2022-03-03 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_alerts_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
