# Generated by Django 3.2.12 on 2022-03-03 19:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alerts_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerts',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
