# Generated by Django 3.2.12 on 2022-03-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_alerts_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='key',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='region',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
